version: '3.4'
services:
    mariadb:
        container_name: cake-store-mariadb
        image: mariadb:10.5
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_USER: user
            MARIADB_DATABASE: cake
            MARIADB_PASSWORD: password
        networks:
            - cake-store-net
        ports:
            - '3376:3306'
        volumes:
            - /mysql:/var/lib/mysql
    backend:
        container_name: cake-store-backend
        build: .
        ports:
            - 8001:8001
        environment:
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_HOST=cake-store-mysql
            - DB_PORT=3306
            - DB_DATABASE=cake
        volumes:
          - .:/app
        networks:
            - cake-store-net
        depends_on:
            - mariadb
networks: 
    cake-store-net: {}
