version: '3.4'
services:
    mysql:
        container_name: cake-store-mysql
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=cake
            - MYSQL_PASSWORD=password
        networks:
            - cake-store-net
        ports:
            - "3376:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
    backend:
        container_name: cake-store-backend
        build: .
        ports:
            - 8001:8001
        environment:
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_HOST=localhost
            - DB_PORT=3306
            - DB_DATABASE=cake
        networks:
            - cake-store-net
        depends_on:
            - mysql
networks: 
    cake-store-net: {}
